"""mahsulot prognoz narx identifikator

Revision ID: 047a9aeaac42
Revises: 3911f72b1e44
Create Date: 2026-08-11 07:30:25.524565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '047a9aeaac42'
down_revision: Union[str, Sequence[str], None] = '3911f72b1e44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('forecast_out_of_stock', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('market_price', sa.Numeric(precision=18, scale=2), nullable=True))
        batch_op.add_column(sa.Column('ikpu', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('seller_item_code', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('article', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('article')
        batch_op.drop_column('seller_item_code')
        batch_op.drop_column('ikpu')
        batch_op.drop_column('market_price')
        batch_op.drop_column('forecast_out_of_stock')

    # ### end Alembic commands ###
