"""mahsulot: jami harakat, narx va olcham ustunlari

Bu ustunlar modelda bor edi, lekin **hech qaysi migratsiyada yo'q edi** —
lokal baza boshqa yo'l bilan yaratilgani uchun sezilmay qolgan. Toza
bazada (ya'ni birinchi production deployda) `products` jadvali ularsiz
yaratilardi va sync birinchi so'rovdayoq yiqilardi.

2026-08-08 da deploydan oldin sxemani modellar bilan solishtirganda
aniqlandi.

Revision ID: 091272516e4d
Revises: be0324ed2575
Create Date: 2026-08-08 07:45:48.789678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '091272516e4d'
down_revision: Union[str, Sequence[str], None] = 'be0324ed2575'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sale_price', sa.Numeric(precision=18, scale=2), nullable=True))
        batch_op.add_column(sa.Column('qty_sold_total', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('qty_returned_total', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('qty_created_total', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('qty_missing', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('qty_defected', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('qty_archived', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('length_mm', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('width_mm', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('height_mm', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('dimensional_group', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('dimensional_group')
        batch_op.drop_column('height_mm')
        batch_op.drop_column('width_mm')
        batch_op.drop_column('length_mm')
        batch_op.drop_column('qty_archived')
        batch_op.drop_column('qty_defected')
        batch_op.drop_column('qty_missing')
        batch_op.drop_column('qty_created_total')
        batch_op.drop_column('qty_returned_total')
        batch_op.drop_column('qty_sold_total')
        batch_op.drop_column('sale_price')

    # ### end Alembic commands ###
