"""birinchi sxema

Revision ID: 0f996dc6a330
Revises: 
Create Date: 2026-08-06 04:17:48.731037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f996dc6a330'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('lang', sa.Enum('UZ', 'RU', name='lang', native_enum=False, length=8), nullable=False),
    sa.Column('oferta_accepted', sa.Boolean(), nullable=False),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_telegram_id'), ['telegram_id'], unique=True)

    op.create_table('shops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('uzum_shop_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'uzum_shop_id', name='uq_shop_user_uzum')
    )
    with op.batch_alter_table('shops', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shops_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shops_uzum_shop_id'), ['uzum_shop_id'], unique=False)

    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan', sa.Enum('TRIAL', 'BASIC', name='plan', native_enum=False, length=16), nullable=False),
    sa.Column('status', sa.Enum('TRIAL', 'ACTIVE', 'EXPIRED', 'CANCELLED', name='subscriptionstatus', native_enum=False, length=16), nullable=False),
    sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscriptions_user_id'), ['user_id'], unique=True)

    op.create_table('alerts_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.Enum('DAILY_REPORT', 'LOW_STOCK', 'SKU_BLOCKED', 'NEW_DISCREPANCY', 'NEW_ORDER', 'RATING_DROP', name='alerttype', native_enum=False, length=32), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('threshold', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'alert_type', name='uq_alert_shop_type')
    )
    with op.batch_alter_table('alerts_config', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_config_shop_id'), ['shop_id'], unique=False)

    op.create_table('claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('doc_path', sa.String(length=512), nullable=True),
    sa.Column('xlsx_path', sa.String(length=512), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('period_from', sa.Date(), nullable=True),
    sa.Column('period_to', sa.Date(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result', sa.Enum('PENDING', 'ACCEPTED', 'PARTIAL', 'REJECTED', name='claimresult', native_enum=False, length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_claims_shop_id'), ['shop_id'], unique=False)

    op.create_table('compensations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('happened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'external_id', name='uq_comp_shop_ext')
    )
    with op.batch_alter_table('compensations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_compensations_shop_id'), ['shop_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_compensations_sku'), ['sku'], unique=False)

    op.create_table('finance_ops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('sku', sa.String(length=64), nullable=True),
    sa.Column('happened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'external_id', name='uq_finance_shop_ext')
    )
    with op.batch_alter_table('finance_ops', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_finance_ops_shop_id'), ['shop_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_ops_sku'), ['sku'], unique=False)
        batch_op.create_index('ix_finance_shop_at', ['shop_id', 'happened_at'], unique=False)

    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('uzum_order_id', sa.String(length=64), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('commission_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('delivery_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('created_at_uzum', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'uzum_order_id', 'sku', name='uq_order_shop_item')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index('ix_order_shop_created', ['shop_id', 'created_at_uzum'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_shop_id'), ['shop_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_sku'), ['sku'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_uzum_order_id'), ['uzum_order_id'], unique=False)

    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('barcode', sa.String(length=128), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('size', sa.String(length=64), nullable=True),
    sa.Column('weight', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('cost_price', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('commission_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'sku', name='uq_product_shop_sku')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_shop_id'), ['shop_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_sku'), ['sku'], unique=False)

    op.create_table('returns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('uzum_return_id', sa.String(length=64), nullable=False),
    sa.Column('order_id', sa.String(length=64), nullable=True),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('returned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'uzum_return_id', 'sku', name='uq_return_shop_item')
    )
    with op.batch_alter_table('returns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_returns_shop_id'), ['shop_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_returns_sku'), ['sku'], unique=False)
        batch_op.create_index(batch_op.f('ix_returns_uzum_return_id'), ['uzum_return_id'], unique=False)

    op.create_table('shop_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('auth_type', sa.Enum('API', 'CABINET', name='authtype', native_enum=False, length=16), nullable=False),
    sa.Column('encrypted_secret', sa.String(length=1024), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'auth_type', name='uq_cred_shop_type')
    )
    with op.batch_alter_table('shop_credentials', schema=None) as batch_op:
        batch_op.create_index('ix_cred_expires', ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_shop_credentials_shop_id'), ['shop_id'], unique=False)

    op.create_table('stock_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('type', sa.Enum('IN', 'SALE', 'RETURN', 'WRITEOFF', name='movementtype', native_enum=False, length=16), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('happened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'external_id', 'sku', name='uq_movement_shop_item')
    )
    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.create_index('ix_movement_shop_at', ['shop_id', 'happened_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_movements_shop_id'), ['shop_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_movements_sku'), ['sku'], unique=False)

    op.create_table('stock_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('warehouse', sa.String(length=64), nullable=False),
    sa.Column('captured_on', sa.Date(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'sku', 'warehouse', 'captured_on', name='uq_snapshot_daily')
    )
    with op.batch_alter_table('stock_snapshots', schema=None) as batch_op:
        batch_op.create_index('ix_snapshot_shop_date', ['shop_id', 'captured_on'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_snapshots_captured_on'), ['captured_on'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_snapshots_shop_id'), ['shop_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_snapshots_sku'), ['sku'], unique=False)

    op.create_table('sync_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('RUNNING', 'SUCCESS', 'FAILED', 'PARTIAL', name='syncstatus', native_enum=False, length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('records_synced', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sync_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_runs_shop_id'), ['shop_id'], unique=False)
        batch_op.create_index('ix_sync_shop_started', ['shop_id', 'started_at'], unique=False)

    op.create_table('discrepancies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.Enum('LOST_STOCK', 'LOST_RETURN', 'OVER_COMMISSION', 'LOGISTICS', 'MISSING_COMPENSATION', name='discrepancykind', native_enum=False, length=32), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('period_from', sa.Date(), nullable=False),
    sa.Column('period_to', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'WATCHING', 'CLAIMED', 'RESOLVED', 'REJECTED', name='discrepancystatus', native_enum=False, length=16), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('claim_doc_path', sa.String(length=512), nullable=True),
    sa.Column('claim_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'sku', 'kind', 'period_from', 'period_to', name='uq_discrepancy_period')
    )
    with op.batch_alter_table('discrepancies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_discrepancies_shop_id'), ['shop_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_discrepancies_sku'), ['sku'], unique=False)
        batch_op.create_index('ix_discrepancy_shop_status', ['shop_id', 'status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discrepancies', schema=None) as batch_op:
        batch_op.drop_index('ix_discrepancy_shop_status')
        batch_op.drop_index(batch_op.f('ix_discrepancies_sku'))
        batch_op.drop_index(batch_op.f('ix_discrepancies_shop_id'))

    op.drop_table('discrepancies')
    with op.batch_alter_table('sync_runs', schema=None) as batch_op:
        batch_op.drop_index('ix_sync_shop_started')
        batch_op.drop_index(batch_op.f('ix_sync_runs_shop_id'))

    op.drop_table('sync_runs')
    with op.batch_alter_table('stock_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_snapshots_sku'))
        batch_op.drop_index(batch_op.f('ix_stock_snapshots_shop_id'))
        batch_op.drop_index(batch_op.f('ix_stock_snapshots_captured_on'))
        batch_op.drop_index('ix_snapshot_shop_date')

    op.drop_table('stock_snapshots')
    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_movements_sku'))
        batch_op.drop_index(batch_op.f('ix_stock_movements_shop_id'))
        batch_op.drop_index('ix_movement_shop_at')

    op.drop_table('stock_movements')
    with op.batch_alter_table('shop_credentials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shop_credentials_shop_id'))
        batch_op.drop_index('ix_cred_expires')

    op.drop_table('shop_credentials')
    with op.batch_alter_table('returns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_returns_uzum_return_id'))
        batch_op.drop_index(batch_op.f('ix_returns_sku'))
        batch_op.drop_index(batch_op.f('ix_returns_shop_id'))

    op.drop_table('returns')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_sku'))
        batch_op.drop_index(batch_op.f('ix_products_shop_id'))

    op.drop_table('products')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_uzum_order_id'))
        batch_op.drop_index(batch_op.f('ix_orders_sku'))
        batch_op.drop_index(batch_op.f('ix_orders_shop_id'))
        batch_op.drop_index('ix_order_shop_created')

    op.drop_table('orders')
    with op.batch_alter_table('finance_ops', schema=None) as batch_op:
        batch_op.drop_index('ix_finance_shop_at')
        batch_op.drop_index(batch_op.f('ix_finance_ops_sku'))
        batch_op.drop_index(batch_op.f('ix_finance_ops_shop_id'))

    op.drop_table('finance_ops')
    with op.batch_alter_table('compensations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_compensations_sku'))
        batch_op.drop_index(batch_op.f('ix_compensations_shop_id'))

    op.drop_table('compensations')
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_claims_shop_id'))

    op.drop_table('claims')
    with op.batch_alter_table('alerts_config', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_config_shop_id'))

    op.drop_table('alerts_config')
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions_user_id'))

    op.drop_table('subscriptions')
    with op.batch_alter_table('shops', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shops_uzum_shop_id'))
        batch_op.drop_index(batch_op.f('ix_shops_user_id'))

    op.drop_table('shops')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_telegram_id'))

    op.drop_table('users')
    # ### end Alembic commands ###
