"""tolovlar jadvali

Revision ID: 1882cd8d4a7e
Revises: 85d8a66cf4b5
Create Date: 2026-08-06 13:54:10.083334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1882cd8d4a7e'
down_revision: Union[str, Sequence[str], None] = '85d8a66cf4b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan', sa.Enum('TRIAL', 'BASIC', 'PRO', name='plan', native_enum=False, length=16), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('months', sa.Integer(), nullable=False),
    sa.Column('method', sa.Enum('TELEGRAM', 'MANUAL', name='paymentmethod', native_enum=False, length=16), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PAID', 'REJECTED', name='paymentstatus', native_enum=False, length=16), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('note', sa.String(length=512), nullable=True),
    sa.Column('confirmed_by', sa.Integer(), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_user_id'))

    op.drop_table('payments')
    # ### end Alembic commands ###
