"""qoldiq yozish jurnali

Revision ID: 5da763607a12
Revises: b83b130e4023
Create Date: 2026-08-09 17:09:58.173626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5da763607a12'
down_revision: Union[str, Sequence[str], None] = 'b83b130e4023'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_write_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.Integer(), nullable=True),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('old_qty', sa.Integer(), nullable=True),
    sa.Column('new_qty', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('APPLIED', 'DEMO', 'FAILED', 'CANCELLED', name='stockwritestatus', native_enum=False, length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock_write_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_write_log_shop_id'), ['shop_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_write_log_sku'), ['sku'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_write_log_telegram_id'), ['telegram_id'], unique=False)
        batch_op.create_index('ix_stock_write_shop_created', ['shop_id', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_write_log', schema=None) as batch_op:
        batch_op.drop_index('ix_stock_write_shop_created')
        batch_op.drop_index(batch_op.f('ix_stock_write_log_telegram_id'))
        batch_op.drop_index(batch_op.f('ix_stock_write_log_sku'))
        batch_op.drop_index(batch_op.f('ix_stock_write_log_shop_id'))

    op.drop_table('stock_write_log')
    # ### end Alembic commands ###
