"""web kabinet tokenlari

Revision ID: 6ae60ac9ccfe
Revises: 878eedf7bd75
Create Date: 2026-08-11 08:43:44.305808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ae60ac9ccfe'
down_revision: Union[str, Sequence[str], None] = '878eedf7bd75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('web_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.Enum('LOGIN', 'SESSION', name='tokenkind', native_enum=False, length=16), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('web_tokens', schema=None) as batch_op:
        batch_op.create_index('ix_web_tokens_expires', ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_web_tokens_telegram_id'), ['telegram_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_web_tokens_token_hash'), ['token_hash'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('web_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_web_tokens_token_hash'))
        batch_op.drop_index(batch_op.f('ix_web_tokens_telegram_id'))
        batch_op.drop_index('ix_web_tokens_expires')

    op.drop_table('web_tokens')
    # ### end Alembic commands ###
