"""qaytarish qoldiqqa qoshildi belgisi

Revision ID: 7544cea4fe9a
Revises: 6ae60ac9ccfe
Create Date: 2026-08-11 20:47:13.279323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7544cea4fe9a'
down_revision: Union[str, Sequence[str], None] = '6ae60ac9ccfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('returns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('restocked_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('returns', schema=None) as batch_op:
        batch_op.drop_column('restocked_at')

    # ### end Alembic commands ###
