"""yunit-iqtisodiyot va olcham maydonlari

Revision ID: 85d8a66cf4b5
Revises: aa94a5ade1e1
Create Date: 2026-08-06 13:24:57.978043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85d8a66cf4b5'
down_revision: Union[str, Sequence[str], None] = 'aa94a5ade1e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seller_profit', sa.Numeric(precision=18, scale=2), nullable=True))
        batch_op.add_column(sa.Column('purchase_price', sa.Numeric(precision=18, scale=2), nullable=True))
        batch_op.add_column(sa.Column('withdrawn_profit', sa.Numeric(precision=18, scale=2), nullable=True))
        batch_op.add_column(sa.Column('return_cause', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('qty_returned', sa.Integer(), nullable=True))

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actual_dimensional_group', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('actual_dimensional_group')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('qty_returned')
        batch_op.drop_column('return_cause')
        batch_op.drop_column('withdrawn_profit')
        batch_op.drop_column('purchase_price')
        batch_op.drop_column('seller_profit')

    # ### end Alembic commands ###
