"""hodimlar va hisobot kanallari

Revision ID: 878eedf7bd75
Revises: 047a9aeaac42
Create Date: 2026-08-11 08:30:00.959110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '878eedf7bd75'
down_revision: Union[str, Sequence[str], None] = '047a9aeaac42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('added_by', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'chat_id', name='uq_channel_shop_chat')
    )
    with op.batch_alter_table('report_channels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_channels_chat_id'), ['chat_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_channels_shop_id'), ['shop_id'], unique=False)

    op.create_table('shop_staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.Enum('VIEWER', 'MANAGER', name='staffrole', native_enum=False, length=16), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('added_by', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'telegram_id', name='uq_staff_shop_tg')
    )
    with op.batch_alter_table('shop_staff', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shop_staff_shop_id'), ['shop_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shop_staff_telegram_id'), ['telegram_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shop_staff', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shop_staff_telegram_id'))
        batch_op.drop_index(batch_op.f('ix_shop_staff_shop_id'))

    op.drop_table('shop_staff')
    with op.batch_alter_table('report_channels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_channels_shop_id'))
        batch_op.drop_index(batch_op.f('ix_report_channels_chat_id'))

    op.drop_table('report_channels')
    # ### end Alembic commands ###
