"""rank, qaytarish foizi, saqlash xarajati

Revision ID: aa94a5ade1e1
Revises: c9b757461b69
Create Date: 2026-08-06 12:58:03.380688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa94a5ade1e1'
down_revision: Union[str, Sequence[str], None] = 'c9b757461b69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rank', sa.String(length=8), nullable=True))
        batch_op.add_column(sa.Column('prev_rank', sa.String(length=8), nullable=True))
        batch_op.add_column(sa.Column('returned_pct', sa.Numeric(precision=6, scale=2), nullable=True))
        batch_op.add_column(sa.Column('paid_storage_amount', sa.Numeric(precision=18, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('paid_storage_amount')
        batch_op.drop_column('returned_pct')
        batch_op.drop_column('prev_rank')
        batch_op.drop_column('rank')

    # ### end Alembic commands ###
