"""mahsulot: FBO qoldiq, olcham, blok holati

Revision ID: c9b757461b69
Revises: 0f996dc6a330
Create Date: 2026-08-06 12:33:43.584270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9b757461b69'
down_revision: Union[str, Sequence[str], None] = '0f996dc6a330'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_blocked', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('block_reason', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('avg_daily_sales', sa.Numeric(precision=12, scale=3), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('avg_daily_sales')
        batch_op.drop_column('status')
        batch_op.drop_column('block_reason')
        batch_op.drop_column('is_blocked')

    # ### end Alembic commands ###
